; Для локальных тестов
; Флаги pytest:
; -vv     максимально подробный вывод
; -s      показывает принты
; --tb=short  короткие traceback'и
; -p no:cacheprovider  отключает кэширование
; --maxfail=3  останавливается после 3 ошибок (закомментировано)

[pytest]
pythonpath = .
addopts = 
    -vv
    -s 
    --tb=short
    -p no:cacheprovider
    ; --maxfail=3

